config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts, only: [:new, :create, :index]
  root 'posts#index'
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signin',  to: 'sessions#create',         via: 'post'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match    '/signup',  to: 'users#new', via: 'get'
  match   '/signup',  to: 'users#create', via: 'post'
  resources :users
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true
  validates :password, length: { minimum: 6 }
  before_create :create_remember_token
  has_many :posts

  # Returns a random token.
  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # include SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  attr_writer :current_user

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :signed_in_user, only: %i[new create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    redirect_to root_path
  end

  def index
    @posts = Post.all
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  # before filter/action
  def signed_in_user
    redirect_to sigin_url unless signed_in?
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    puts 'hello'
    user = User.find_by(email: params[:session][:email].downcase)
    puts 'bye'
    if user&.authenticate(params[:session][:password])
      flash[:success] = 'Thank you for signing in!'
      sign_in user
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:info] = 'Account created successfully'
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="background">
  <head >
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
  </head>

  <body>
    <div>
      <% flash.each do |message_type, message| %>
        <button class="delete"></button>  
        <%= content_tag(:div, message, class: "notification is-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>

    <script>
      document.addEventListener('DOMContentLoaded', () => {
        (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
          $notification = $delete.parentNode;
          $delete.addEventListener('click', () => {
            $notification.parentNode.removeChild($notification);
          });
        });
    });
    </script> 
  </body>
</html>

app/views/posts/index.html.erb
<div class="container">
<div class="float-right">
  <% if signed_in? %>
  <a class="button is-link is-light" data-method="delete" href="/signout"><%="(#{current_user.name})" %> Sign out</a>
  <% else %>
    <%= link_to 'Sign in', signin_path, { :class=>"button is-link is-light" } %>
  <% end %>
</div>

<div class="columns">
  <div class="column"></div>
  <div class="column"><h3 class="title is-3">Members Only Posts</h3></div>
  <div class="column"></div>
  
</div>


<% @posts.each do |post| %>
<div class="box">
  <article class="media">
    <div class="media-left">
      <figure class="image is-64x64">
        <%= image_tag "images.png" %>
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
      <% if signed_in? %>
        <h4><%=post.title %></h4><br>
        <p>
          <strong>Posted by: <%= post.user.name %></strong> 
          <br>
          <%= post.body %>
        </p>

        <% else %>
        <h4><%=post.title %></h4><br>
        <p>
          <%= post.body %>
        </p>

        <% end %> 
      </div>
      
    </div>
  </article>
</div>
<% end %>
<% if signed_in? %>
  <%= link_to "Create a Post", new_post_path,  { :class=>"button is-link is-light" } %>
<% end %>
</div>

app/views/posts/new.html.erb
<section class="hero is-success is-fullheight">
  <div class="hero-body">
    <div class="container has-text-centered">
      <div class="column is-4 is-offset-4">
        <h3 class="title has-text-black">Posts</h3>
        <hr class="login-hr">
        <p class="subtitle has-text-black">New Posts</p>
          <div class="box">
            <%= form_for @post do |f| %>
            <div class="field">
              <div class="control">
                <%= f.text_field :title, class: 'input is-large', placeholder: 'Title' %>
              </div>
            </div>
            <div class="field">
              <label class="label">Message</label>
                <div class="control">
                  <%= f.text_area :body, class: 'textarea', placeholder: 'Your text' %>
                  </div>
                </div>
              <div class="field">         
            </div>
            <%= f.submit "New Post", class: "button is-block is-info is-large is-fullwidth" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="notification is-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<!-- <% provide(:title, 'Sign up') %> -->
<section class="hero is-success is-fullheight">
  <div class="hero-body">
    <div class="container has-text-centered">
      <div class="column is-4 is-offset-4">
        <h3 class="title has-text-black">Sign Up</h3>
        <hr class="login-hr">
        <p class="subtitle has-text-black">Please create an account.</p>
        <div class="box">
          <figure class="avatar">
             <%= image_tag "images.png" %>
          </figure>
          <%= form_for(@user) do |f| %>
          <%= render 'shared/error_messages' %>
          <div class="field">
            <div class="control">
              <%= f.text_field :name, class: 'input is-large form-control', placeholder: 'Your Name' %>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <%= f.email_field :email, class: 'input is-large form-control', placeholder: 'Your Email' %>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <%= f.password_field :password, class: 'input is-large form-control', placeholder: 'Your Password' %>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <%= f.password_field :password_confirmation, class: 'input is-large form-control', placeholder: 'Password Confirmation' %>
            </div>
          </div>
          <%= f.submit "Create my account", class: "button is-block is-info is-large is-fullwidth" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>